# Array Creation

In [2]:
# np.array() - creates numpy array from the list or tuple.
import numpy as np
arr = np.array([1, 2, 3])
print(arr)

[1 2 3]


In [3]:
# np.zeros() - creats array filled with zeros
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
# np.dull() - creates an array with constant values
np.full((2, 2), 4)

array([[4, 4],
       [4, 4]])